# Generated by Django 2.1.4 on 2019-01-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crapp', '0002_auto_20190106_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doors',
            name='bedroom',
        ),
        migrations.RemoveField(
            model_name='doors',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='doors',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='handles',
            name='bedroom',
        ),
        migrations.RemoveField(
            model_name='handles',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='handles',
            name='kitchen',
        ),
    ]
